name: conecta_gb
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_clean_architecture: 
    git: https://github.com/zuse1991/flutter_clean_architecture.git
  bdd_widget_test: ^1.3.2+1
  flutter_i18n: ^0.32.2
  logger: ^1.1.0
  dio: ^4.0.6
  crypto: ^3.0.2
  mockito: ^5.2.0
  cached_network_image: ^3.2.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/images/
